# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="A single word, to use as key in popovers' inclusion tags", max_length=255, unique=True)),
                ('name', models.CharField(blank=True, help_text='The term', max_length=255, verbose_name='Term')),
                ('definition', models.TextField(blank=True, help_text='The definition of the term', verbose_name='Definition')),
                ('main_term', models.ForeignKey(blank=True, help_text='Main definition', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='idioticon.Term')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
            },
        ),
    ]
